package model;

import java.time.LocalDateTime;

public class CarBrand {

    private Integer maHang;
    private String tenHang;
    private String moTa;
    private LocalDateTime ngayTao;
    private LocalDateTime ngayCapNhat;
    private String trangThai; // Ví dụ: "Hoạt động", "Không hoạt động"

    public CarBrand() {
    }

    // Full constructor for retrieving from DB
    public CarBrand(Integer maHang, String tenHang, String moTa, LocalDateTime ngayTao, LocalDateTime ngayCapNhat, String trangThai) {
        this.maHang = maHang;
        this.tenHang = tenHang;
        this.moTa = moTa;
        this.ngayTao = ngayTao;
        this.ngayCapNhat = ngayCapNhat;
        this.trangThai = trangThai;
    }

    // Constructor for new creation (maHang will be auto-generated by DB)
    public CarBrand(String tenHang, String moTa) {
        this.tenHang = tenHang;
        this.moTa = moTa;
        this.ngayTao = LocalDateTime.now();
        this.trangThai = "Hoạt động"; // Default status
    }

    // Getters and Setters
    public Integer getMaHang() {
        return maHang;
    }

    public void setMaHang(Integer maHang) {
        this.maHang = maHang;
    }

    public String getTenHang() {
        return tenHang;
    }

    public void setTenHang(String tenHang) {
        this.tenHang = tenHang;
    }

    public String getMoTa() {
        return moTa;
    }

    public void setMoTa(String moTa) {
        this.moTa = moTa;
    }

    public LocalDateTime getNgayTao() {
        return ngayTao;
    }

    public void setNgayTao(LocalDateTime ngayTao) {
        this.ngayTao = ngayTao;
    }

    public LocalDateTime getNgayCapNhat() {
        return ngayCapNhat;
    }

    public void setNgayCapNhat(LocalDateTime ngayCapNhat) {
        this.ngayCapNhat = ngayCapNhat;
    }

    public String getTrangThai() {
        return trangThai;
    }

    public void setTrangThai(String trangThai) {
        this.trangThai = trangThai;
    }
}
