package model;

import java.time.LocalDateTime;

public class CarModel {
    private Integer maDong;
    private Integer maHang; // Foreign key to CarBrand
    private String tenDong;
    private String loaiXe; // Ví dụ: "Sedan", "SUV", "Hatchback", "Truck"
    private Integer soChoNgoi;
    private String loaiHopSo; // Ví dụ: "Tự động", "Số sàn"
    private String loaiNhienLieu; // Ví dụ: "Xăng", "Dầu Diesel", "Điện", "Hybrid"
    private String moTa;
    private LocalDateTime ngayTao;
    private LocalDateTime ngayCapNhat;
    private String trangThai; // Ví dụ: "Đang sản xuất", "Ngừng sản xuất"

    // Associated object
    private CarBrand hangXe; // For convenience when retrieving full data

    public CarModel() {
    }

    // Full constructor for retrieving from DB
    public CarModel(Integer maDong, Integer maHang, String tenDong, String loaiXe, Integer soChoNgoi, String loaiHopSo, String loaiNhienLieu, String moTa, LocalDateTime ngayTao, LocalDateTime ngayCapNhat, String trangThai) {
        this.maDong = maDong;
        this.maHang = maHang;
        this.tenDong = tenDong;
        this.loaiXe = loaiXe;
        this.soChoNgoi = soChoNgoi;
        this.loaiHopSo = loaiHopSo;
        this.loaiNhienLieu = loaiNhienLieu;
        this.moTa = moTa;
        this.ngayTao = ngayTao;
        this.ngayCapNhat = ngayCapNhat;
        this.trangThai = trangThai;
    }

    // Constructor for new creation (maDong will be auto-generated by DB)
    public CarModel(Integer maHang, String tenDong, String loaiXe, Integer soChoNgoi, String loaiHopSo, String loaiNhienLieu, String moTa) {
        this.maHang = maHang;
        this.tenDong = tenDong;
        this.loaiXe = loaiXe;
        this.soChoNgoi = soChoNgoi;
        this.loaiHopSo = loaiHopSo;
        this.loaiNhienLieu = loaiNhienLieu;
        this.moTa = moTa;
        this.ngayTao = LocalDateTime.now();
        this.trangThai = "Đang sản xuất"; // Default status
    }

    // Getters and Setters
    public Integer getMaDong() {
        return maDong;
    }

    public void setMaDong(Integer maDong) {
        this.maDong = maDong;
    }

    public Integer getMaHang() {
        return maHang;
    }

    public void setMaHang(Integer maHang) {
        this.maHang = maHang;
    }

    public String getTenDong() {
        return tenDong;
    }

    public void setTenDong(String tenDong) {
        this.tenDong = tenDong;
    }

    public String getLoaiXe() {
        return loaiXe;
    }

    public void setLoaiXe(String loaiXe) {
        this.loaiXe = loaiXe;
    }

    public Integer getSoChoNgoi() {
        return soChoNgoi;
    }

    public void setSoChoNgoi(Integer soChoNgoi) {
        this.soChoNgoi = soChoNgoi;
    }

    public String getLoaiHopSo() {
        return loaiHopSo;
    }

    public void setLoaiHopSo(String loaiHopSo) {
        this.loaiHopSo = loaiHopSo;
    }

    public String getLoaiNhienLieu() {
        return loaiNhienLieu;
    }

    public void setLoaiNhienLieu(String loaiNhienLieu) {
        this.loaiNhienLieu = loaiNhienLieu;
    }

    public String getMoTa() {
        return moTa;
    }

    public void setMoTa(String moTa) {
        this.moTa = moTa;
    }

    public LocalDateTime getNgayTao() {
        return ngayTao;
    }

    public void setNgayTao(LocalDateTime ngayTao) {
        this.ngayTao = ngayTao;
    }

    public LocalDateTime getNgayCapNhat() {
        return ngayCapNhat;
    }

    public void setNgayCapNhat(LocalDateTime ngayCapNhat) {
        this.ngayCapNhat = ngayCapNhat;
    }

    public String getTrangThai() {
        return trangThai;
    }

    public void setTrangThai(String trangThai) {
        this.trangThai = trangThai;
    }

    // Getter/Setter for associated CarBrand
    public CarBrand getHangXe() {
        return hangXe;
    }

    public void setHangXe(CarBrand hangXe) {
        this.hangXe = hangXe;
    }
}