package model;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.math.BigDecimal; // Keep BigDecimal for now if needed elsewhere, but constructor uses Long

public class Customer {

    private Integer maKH;
    private String hoTen;
    private LocalDate ngaySinh;
    private String gioiTinh;
    private String diaChi;
    private String soDienThoai;
    private String email;
    private String cccd;
    private String ngheNghiep;
    private BigDecimal mucThuNhap; // Consider if this should be Long or BigDecimal consistently
    private LocalDateTime ngayTao;
    private String trangThai;

    public Customer() {
    }

    // Original full constructor (uses BigDecimal for mucThuNhap)
    public Customer(Integer maKH, String hoTen, LocalDate ngaySinh, String gioiTinh, String diaChi, String soDienThoai, String email, String cccd, String ngheNghiep, BigDecimal mucThuNhap, LocalDateTime ngayTao, String trangThai) {
        this.maKH = maKH;
        this.hoTen = hoTen;
        this.ngaySinh = ngaySinh;
        this.gioiTinh = gioiTinh;
        this.diaChi = diaChi;
        this.soDienThoai = soDienThoai;
        this.email = email;
        this.cccd = cccd;
        this.ngheNghiep = ngheNghiep;
        this.mucThuNhap = mucThuNhap;
        this.ngayTao = ngayTao;
        this.trangThai = trangThai;
    }

    // Constructor for new creation (ID will be auto-generated by DB)
    public Customer(String hoTen, LocalDate ngaySinh, String gioiTinh, String diaChi, String soDienThoai, String email, String cccd, String ngheNghiep, BigDecimal mucThuNhap) {
        this.hoTen = hoTen;
        this.ngaySinh = ngaySinh;
        this.gioiTinh = gioiTinh;
        this.diaChi = diaChi;
        this.soDienThoai = soDienThoai;
        this.email = email;
        this.cccd = cccd;
        this.ngheNghiep = ngheNghiep;
        this.mucThuNhap = mucThuNhap;
        this.ngayTao = LocalDateTime.now();
        this.trangThai = "Hoạt động";
    }

    // --- NEW CONSTRUCTOR ADDED HERE ---
    // Constructor to map directly from ResultSet, using Long for mucThuNhap for this specific constructor
    public Customer(Integer maKH, String hoTen, LocalDate ngaySinh, String gioiTinh, String diaChi,
            String soDienThoai, String email, String cccd, String ngheNghiep,
            Long mucThuNhap, LocalDateTime ngayTao, String trangThai) {
        this.maKH = maKH;
        this.hoTen = hoTen;
        this.ngaySinh = ngaySinh;
        this.gioiTinh = gioiTinh;
        this.diaChi = diaChi;
        this.soDienThoai = soDienThoai;
        this.email = email;
        this.cccd = cccd;
        this.ngheNghiep = ngheNghiep;
        // Convert Long to BigDecimal if 'this.mucThuNhap' is BigDecimal, otherwise keep as Long
        // If 'mucThuNhap' field in Customer class is BigDecimal:
        this.mucThuNhap = (mucThuNhap != null) ? new BigDecimal(mucThuNhap) : null;
        // If 'mucThuNhap' field in Customer class should be Long:
        // this.mucThuNhap = mucThuNhap; // Requires changing field type from BigDecimal to Long
        this.ngayTao = ngayTao;
        this.trangThai = trangThai;
    }
    // ------------------------------------

    // Getters and Setters (ensure consistency with type of mucThuNhap field)
    public Integer getMaKH() {
        return maKH;
    }

    public void setMaKH(Integer maKH) {
        this.maKH = maKH;
    }

    public String getHoTen() {
        return hoTen;
    }

    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }

    public LocalDate getNgaySinh() {
        return ngaySinh;
    }

    public void setNgaySinh(LocalDate ngaySinh) {
        this.ngaySinh = ngaySinh;
    }

    public String getGioiTinh() {
        return gioiTinh;
    }

    public void setGioiTinh(String gioiTinh) {
        this.gioiTinh = gioiTinh;
    }

    public String getDiaChi() {
        return diaChi;
    }

    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }

    public String getSoDienThoai() {
        return soDienThoai;
    }

    public void setSoDienThoai(String soDienThoai) {
        this.soDienThoai = soDienThoai;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getCccd() {
        return cccd;
    }

    public void setCccd(String cccd) {
        this.cccd = cccd;
    }

    public String getNgheNghiep() {
        return ngheNghiep;
    }

    public void setNgheNghiep(String ngheNghiep) {
        this.ngheNghiep = ngheNghiep;
    }

    public BigDecimal getMucThuNhap() { // This getter returns BigDecimal
        return mucThuNhap;
    }

    public void setMucThuNhap(BigDecimal mucThuNhap) { // This setter accepts BigDecimal
        this.mucThuNhap = mucThuNhap;
    }

    public LocalDateTime getNgayTao() {
        return ngayTao;
    }

    public void setNgayTao(LocalDateTime ngayTao) {
        this.ngayTao = ngayTao;
    }

    public String getTrangThai() {
        return trangThai;
    }

    public void setTrangThai(String trangThai) {
        this.trangThai = trangThai;
    }
}
