package model;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.sql.Date; // Important: import java.sql.Date for the helper method

public class Employee {

    private Integer maNV;
    private Integer maUser; // Added to link to the Users table (Important for the full model)
    private String hoTen;
    private LocalDate ngaySinh;
    private String gioiTinh;
    private String diaChi;
    private String soDienThoai;
    private String email;
    private String cccd;
    private String chucVu;
    private String phongBan; // Added this field
    private LocalDate ngayVaoLam;
    private BigDecimal luongCoBan;
    private BigDecimal heSoLuong; // Added this field
    private String trangThai;
    private LocalDateTime ngayTao;
    private LocalDateTime ngayCapNhat;

    public Employee() {
    }

    // Existing Full constructor for retrieval from DB (if maUser, phongBan, heSoLuong are always available)
    public Employee(Integer maNV, Integer maUser, String hoTen, LocalDate ngaySinh, String gioiTinh, String diaChi, String soDienThoai, String email, String cccd, String chucVu, String phongBan, LocalDate ngayVaoLam, BigDecimal luongCoBan, BigDecimal heSoLuong, String trangThai, LocalDateTime ngayTao, LocalDateTime ngayCapNhat) {
        this.maNV = maNV;
        this.maUser = maUser; // Make sure you're getting this from DB if needed
        this.hoTen = hoTen;
        this.ngaySinh = ngaySinh;
        this.gioiTinh = gioiTinh;
        this.diaChi = diaChi;
        this.soDienThoai = soDienThoai;
        this.email = email;
        this.cccd = cccd;
        this.chucVu = chucVu;
        this.phongBan = phongBan;
        this.ngayVaoLam = ngayVaoLam;
        this.luongCoBan = luongCoBan;
        this.heSoLuong = heSoLuong;
        this.trangThai = trangThai;
        this.ngayTao = ngayTao;
        this.ngayCapNhat = ngayCapNhat;
    }

    // Constructor for creating new Employee (MaNV will be auto-generated by DB)
    public Employee(Integer maUser, String hoTen, LocalDate ngaySinh, String gioiTinh, String diaChi, String soDienThoai, String email, String cccd, String chucVu, String phongBan, LocalDate ngayVaoLam, BigDecimal luongCoBan, BigDecimal heSoLuong) {
        this.maUser = maUser;
        this.hoTen = hoTen;
        this.ngaySinh = ngaySinh;
        this.gioiTinh = gioiTinh;
        this.diaChi = diaChi;
        this.soDienThoai = soDienThoai;
        this.email = email;
        this.cccd = cccd;
        this.chucVu = chucVu;
        this.phongBan = phongBan;
        this.ngayVaoLam = ngayVaoLam;
        this.luongCoBan = luongCoBan;
        this.heSoLuong = heSoLuong;
        this.trangThai = "Đang làm việc"; // Default status
        this.ngayTao = LocalDateTime.now();
    }

    // --- NEW CONSTRUCTOR BASED ON YOUR `while (rs.next())` LOOP ---
    // IMPORTANT: This constructor does NOT include 'maUser', 'phongBan', or 'heSoLuong'
    // if those are part of your Employee table, you might need to adjust your SQL query
    // to retrieve them, or modify this constructor to take them if they can be null.
    public Employee(Integer maNV, String hoTen, LocalDate ngaySinh, String gioiTinh,
            String diaChi, String soDienThoai, String email, String cccd,
            String chucVu, LocalDate ngayVaoLam, BigDecimal luongCoBan,
            String trangThai, LocalDateTime ngayTao, LocalDateTime ngayCapNhat) {
        this.maNV = maNV;
        // maUser is missing from your provided constructor call, so it will be null or default
        // this.maUser = null; // or retrieve it if your query includes it

        this.hoTen = hoTen;
        this.ngaySinh = ngaySinh;
        this.gioiTinh = gioiTinh;
        this.diaChi = diaChi;
        this.soDienThoai = soDienThoai;
        this.email = email;
        this.cccd = cccd;
        this.chucVu = chucVu;
        // phongBan is missing from your provided constructor call, so it will be null or default
        // this.phongBan = null; // or retrieve it if your query includes it

        this.ngayVaoLam = ngayVaoLam;
        this.luongCoBan = luongCoBan;
        // heSoLuong is missing from your provided constructor call, so it will be null or default
        // this.heSoLuong = null; // or retrieve it if your query includes it

        this.trangThai = trangThai;
        this.ngayTao = ngayTao;
        this.ngayCapNhat = ngayCapNhat;
    }
    // --- END NEW CONSTRUCTOR ---

    // Getters and Setters (no changes needed for these)
    public Integer getMaNV() {
        return maNV;
    }

    public void setMaNV(Integer maNV) {
        this.maNV = maNV;
    }

    public Integer getMaUser() {
        return maUser;
    }

    public void setMaUser(Integer maUser) {
        this.maUser = maUser;
    }

    public String getHoTen() {
        return hoTen;
    }

    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }

    public LocalDate getNgaySinh() {
        return ngaySinh;
    }

    public void setNgaySinh(LocalDate ngaySinh) {
        this.ngaySinh = ngaySinh;
    }

    public String getGioiTinh() {
        return gioiTinh;
    }

    public void setGioiTinh(String gioiTinh) {
        this.gioiTinh = gioiTinh;
    }

    public String getDiaChi() {
        return diaChi;
    }

    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }

    public String getSoDienThoai() {
        return soDienThoai;
    }

    public void setSoDienThoai(String soDienThoai) {
        this.soDienThoai = soDienThoai;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getCccd() {
        return cccd;
    }

    public void setCccd(String cccd) {
        this.cccd = cccd;
    }

    public String getChucVu() {
        return chucVu;
    }

    public void setChucVu(String chucVu) {
        this.chucVu = chucVu;
    }

    public String getPhongBan() {
        return phongBan;
    }

    public void setPhongBan(String phongBan) {
        this.phongBan = phongBan;
    }

    public LocalDate getNgayVaoLam() {
        return ngayVaoLam;
    }

    public void setNgayVaoLam(LocalDate ngayVaoLam) {
        this.ngayVaoLam = ngayVaoLam;
    }

    public BigDecimal getLuongCoBan() {
        return luongCoBan;
    }

    public void setLuongCoBan(BigDecimal luongCoBan) {
        this.luongCoBan = luongCoBan;
    }

    public BigDecimal getHeSoLuong() {
        return heSoLuong;
    }

    public void setHeSoLuong(BigDecimal heSoLuong) {
        this.heSoLuong = heSoLuong;
    }

    public String getTrangThai() {
        return trangThai;
    }

    public void setTrangThai(String trangThai) {
        this.trangThai = trangThai;
    }

    public LocalDateTime getNgayTao() {
        return ngayTao;
    }

    public void setNgayTao(LocalDateTime ngayTao) {
        this.ngayTao = ngayTao;
    }

    public LocalDateTime getNgayCapNhat() {
        return ngayCapNhat;
    }

    public void setNgayCapNhat(LocalDateTime ngayCapNhat) {
        this.ngayCapNhat = ngayCapNhat;
    }

    // Helper method to convert LocalDate to java.sql.Date
    public java.sql.Date getNgayVaoLamAsSqlDate() {
        return (ngayVaoLam != null) ? java.sql.Date.valueOf(ngayVaoLam) : null;
    }

    // Helper method for NgaySinh (if it was LocalDate, but currently is LocalDate)
    public java.sql.Date getNgaySinhAsSqlDate() {
        return (ngaySinh != null) ? java.sql.Date.valueOf(ngaySinh) : null;
    }
}
